### ISSUE TITLE
Failed to load a language-elm-treesitter package grammar

### ISSUE THREAD

**Issue by smucode** [GrayJack/language-elm-treesitter#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: [language-elm-treesitter](https://github.com/GrayJack/language-elm-treesitter) package 0.2.2

### Stack Trace

Failed to load a language-elm-treesitter package grammar

```
At The module '/Users/smu/.atom/packages/language-elm-treesitter/node_modules/tree-sitter-elm/build/Release/tree_sitter_elm_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/smu/.atom/packages/language-elm-treesitter/grammars/tree-sitter-elm.cson

Error: The module '/Users/smu/.atom/packages/language-elm-treesitter/node_modules/tree-sitter-elm/build/Release/tree_sitter_elm_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/language-elm-treesitter/node_modules/tree-sitter-elm/index.js:2:20)
    at /packages/language-elm-treesitter/node_modules/tree-sitter-elm/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3116620)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360231)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360072
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:581958
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
  at /packages/language-elm-treesitter/grammars/tree-sitter-elm.cson:1:1
```

### Commands

```
     -0:17.3.0 project-find:show (input.hidden-input)
     -0:17.1.0 core:paste (input.hidden-input)
     -0:01.3.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 13.6.0 
busy-signal 2.0.1 
elm-sm 0.2.3 
goto-definition 1.3.4 
intentions 1.1.5 
language-elm 1.5.0 
language-elm-treesitter 0.2.2 
linter 2.3.1 
linter-ui-default 1.8.1 
prettier-atom 0.59.0 
```

**Comment by staeter** [comment]
Have the same issue with pretty much the same setup
